### ISSUE TITLE
Different JSON mappings for N3-HV-10.0 

### ISSUE THREAD

**Issue by lwag-s** [gastush/ha-renac#19]
Hey, 

I just found out about your integration and I am very thankful for you getting me started with my Renac inverter inside of HA.

Sadly the integration didnt work right on the first try. I had to debug the custom component inside of HA and I recreated some parts using Postman and python. When fetching the data, it seems like everything works until the values inside the JSON are returned. I checked your definition, it turned out to be wrongly mapped. 

These are the keys that were returned from the API:
`{
    "success": true,
    "messageCode": 200000,
    "message": "操作成功",
    "results": {
        "ESP_CUR": 0.0,
        "ESP_CUR_T": 0.0,
        "T_VOL": 233.9,
        "PV": 1615.0,
        "ESP_POWER_R": 0.0,
        "S_CUR": 2.7,
        "ENERGY_TOTAL": 609.1,
        "FACTORY_NAME": "纳通能源",
        "ENERGY_TODAY": 7.2,
        "INV_SN": "redacted",
        "BATTERY_CAPACITY": 10.0,
        "ESP_CUR_R": 0.0,
        "ESP_CUR_S": 0.0,
        "ESP_POWER_S": 0.0,
        "T_POWER": 593.0,
        "ESP_POWER_T": 0.0,
        "STATUS": 0,
        "ESP_VOL": 0.0,
        "max_charge_current": 0,
        "R_CUR": 2.8,
        "INV_DETAIL_KIND": 1,
        "AC": 1714.0,
        "B_POWER": 0.0,
        "G_VOL": 234.7,
        "S_POWER": 535.0,
        "limit_discharge_vol": 0,
        "IMG_PATH": "https://lepv-system.oss-cn-hangzhou.aliyuncs.com/equipment/",
        "G_CUR": -5.747763101832127,
        "PV2_VOL": 451.7,
        "max_discharge_current": 0,
        "LOAD": 266.0,
        "ESP_POWER": 0.0,
        "ESP_VOL_T": 0.0,
        "ESP_VOL_S": 0.0,
        "ESP_VOL_R": 0.0,
        "PV1_VOL": 207.7,
        "FACTORY_NAME_EN": "RENAC",
        "soc_max_min": 0,
        "limit_charge_vol": 0,
        "PV1_POWER": 352.0,
        "ON_DAY": 0,
        "IMG_NAME": "RENACPOWER.png",
        "PV1_CUR": 1.8,
        "R_POWER": 586.0,
        "MEMO2": 10000.0,
        "GRID": -1349.0,
        "TIME": "",
        "B_CUR": 0.0,
        "PV2_CUR": 2.9,
        "ADDR_485": 1,
        "G_POWER": -1349.0,
        "EQUMODEL_NAME": "N3-HV-10.0",
        "CAPACITY_CHARGE": 97.0,
        "BAT": 0.0,
        "judgeStatus": 0,
        "TMP": 42.0,
        "R_VOL": 234.7,
        "bat_type": 1,
        "B_VOL": 201.9,
        "S_VOL": 231.7,
        "PV2_POWER": 1263.0,
        "battery_capacity": 10.0,
        "RUN_MODE": 0,
        "T_CUR": 2.9
    }
}`

I have adapted your sensor.py to this:
[sensor_py.txt](https://github.com/gastush/ha-renac/files/14667499/sensor_py.txt)

Maybe you could consider allowing different configurations for different devices.
Id be glad helping you out what each value means if its necessary. Also: do you have a complete API reference guide?

Best regards!

**Comment by gastush** [comment]
Hello,

Sorry for the late reply, I was away on a business trip. I already got the request to support Hybrid inverter, but had no time to work on it yet. Thanks to your sample data and your proposal I may progress a bit on that one. The idea being to make it dynamic based on the inverter type. I'll try to integrate your changes and adapt them a bit. I'll push a pre-release as soon as I can.
Feel free to contribute also by cloning the repo and submitting a PR

The API Specs can be found here : https://github.com/gastush/ha-renac/files/14135575/1693416026158-renac-sec-api-document-v2.0.7.pdf

Kind Regards

**Comment by lwag-s** [comment]
Thanks for the reply.
Sadly, the integration crashed a few days ago, and it needed a home assistant restart to work again.

The API Specs are the same as I have, but it seems like the API you connected with your service is a different one. For example, I can't find "equipDetail" in the given document.

Id like to contribute more, but I'd need to learn more about HA component deployment first.

**Comment by pkontopos** [comment]
Hi I am new in home assistant , I have the N3-HV-6.0 inverter and both sensor.py didn't work .

KeyError: 'email'
2024-12-12 19:12:52.025 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.renac_total_generated_power_3 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1320, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/renac/sensor.py", line 150, in update
    self._attr_native_value = self.updater.fetch(self.field)
                              ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/config/custom_components/renac/sensor.py", line 42, in fetch
    loginResponse = login(self.config.get(CONF_USERNAME), self.config.get(CONF_PASSWORD))
  File "/config/custom_components/renac/sensor.py", line 92, in login
    _LOGGER.info("Got email id :" + str(r.json()['email']))
                                        ~~~~~~~~^^^^^^^^^

**Comment by gastush** [comment]
Hello @pkontopos, the Hybrid Inverter are not supported (yet). This simply because I don't have one. I've been re-writing the whole integration from scratch recently and I hope to push a new version soon that will support both the On-Grid and Hybrid inverter. Your testing will be appreciated. I'll keep you posted.

**Comment by pkontopos** [comment]
Thanks for updating, of course you can send me message for testing , I will be happy to contribute !!

**Comment by gastush** [comment]
@lwag-s, @pkontopos, I Just issued a 0.1.3 version that should support the N3-HV kind of inverter (not tested, but based on your input)
Give it a try and let me know
